### ISSUE TITLE
Docker를 사용하기 위한 개발환경 구성

### ISSUE THREAD

**Issue by lmw7414** [lmw7414/Pharmacy-Recommendation#3]
Docker를 사용하기 위해 개발환경을 구성한다.

## Todo
* [x] docker 설치
* [x] docker-compose 설치
* [x] 도커 파일 생성
  * [x] root 애플리케이션
  * [x] database(mariadb)
    * [x] 한글 깨짐을 막기 위한 추가설정 
  * [x] redis
* [x] 환경 별 profile 분리하기
