### ISSUE TITLE
약국 도메인 생성 및 Kakao 주소 검색 API 구현하기

### ISSUE THREAD

**Issue by lmw7414** [lmw7414/Pharmacy-Recommendation#5]
KakaoAPI를 통해 현재 위치의 위도 경도를 반환하는 기능을 개발한다.
## Todo
* [x] [kakao 주소 검색 api 스펙 살펴보기](https://developers.kakao.com/docs/latest/ko/local/dev-guide)
  * [x] API 호출제한 확인
  * [x] 애플리케이션 등록
  * [x] 키 정보 확인
  * [x] REST API 테스트 도구를 활용하여 API 테스트
* [x] 주소정보 -> 위도 경도로 변환하기
* [x] 약국 도메인 생성

**Comment by lmw7414** [comment]
### API호출제한 확인하기
* https://developers.kakao.com/docs/latest/ko/quota/common
*  하루 100,000건 확인
